<?php

namespace ContainerOCfEfD2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HZ6q4r9.App\Entity\Channel' shared service.
     *
     * @return \App\Entity\Channel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HZ6q4r9": it references class "App\\Entity\\Channel" but no such service exists.');
    }
}
