<?php

namespace ContainerOoJZDbJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZ6q4r9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HZ6q4r9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZ6q4r9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'channel' => ['privates', '.errored..service_locator.HZ6q4r9.App\\Entity\\Channel', NULL, 'Cannot autowire service ".service_locator.HZ6q4r9": it references class "App\\Entity\\Channel" but no such service exists.'],
            'cookieJwtProvider' => ['privates', 'App\\Services\\Mercure\\CookieJwtProvider', 'getCookieJwtProviderService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'channel' => 'App\\Entity\\Channel',
            'cookieJwtProvider' => 'App\\Services\\Mercure\\CookieJwtProvider',
            'messageRepository' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
