<?php

namespace ContainerIS1pfSr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AtEbSfUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.atEbSfU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.atEbSfU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'channelRepository' => ['privates', 'App\\Repository\\ChannelRepository', 'getChannelRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'publisher' => ['privates', 'mercure.hub.default.traceable', 'getMercure_Hub_Default_TraceableService', true],
            'repoUser' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'channelRepository' => 'App\\Repository\\ChannelRepository',
            'em' => '?',
            'publisher' => '?',
            'repoUser' => 'App\\Repository\\UserRepository',
            'serializer' => '?',
        ]);
    }
}
