<?php

namespace ContainerIS1pfSr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookieJwtProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Mercure\CookieJwtProvider' shared autowired service.
     *
     * @return \App\Services\Mercure\CookieJwtProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'Mercure'.\DIRECTORY_SEPARATOR.'CookieJwtProvider.php';

        return $container->privates['App\\Services\\Mercure\\CookieJwtProvider'] = new \App\Services\Mercure\CookieJwtProvider($container->getEnv('MERCURE_JWT_KEY'));
    }
}
