<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIS1pfSr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIS1pfSr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIS1pfSr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIS1pfSr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIS1pfSr\App_KernelDevDebugContainer([
    'container.build_hash' => 'IS1pfSr',
    'container.build_id' => '3d6d6ac4',
    'container.build_time' => 1636558190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIS1pfSr');
