<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'chat_channel' => [[], ['_controller' => 'App\\Controller\\ChatController::getChannels'], [], [['text', '/chat']], [], []],
    'chat' => [['id'], ['_controller' => 'App\\Controller\\ChatController::chat'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chat']], [], []],
    'message' => [[], ['_controller' => 'App\\Controller\\ChatController::sendMessage'], [], [['text', '/message']], [], []],
    'app_channel_new' => [[], ['_controller' => 'App\\Controller\\ChatController::register'], [], [['text', '/new_channel']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\ProfilController::modifierImage'], [], [['text', '/profil/']], [], []],
    'app_supprimer_image' => [[], ['_controller' => 'App\\Controller\\ProfilController::deleteImage'], [], [['text', '/profil/image/supprimer']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/user']], [], []],
    'user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
